export const FULL_DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
export const COMPACT_DATE_TIME_FORMAT = 'YYYYMMDDHHmm';
export const COMPACT_DATE_TIME_WITH_SECOND_FORMAT = 'YYYYMMDDHHmmss';
export const CLIENT_ONLINE_STATUS = 'RSMS_CLIENT_ONLINE_STATUS';
